services:
  db:
    image: pgvector/pgvector:pg17  # Prebuilt Postgres image with pgvector
    container_name: postgres-pgvector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${MY_ENV_NAME}
      POSTGRES_PASSWORD: ${MY_ENV_PASSWORD}
      POSTGRES_DB: ${MY_ENV_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

